const { faker } = require('@faker-js/faker');

Feature('Onboarding');

Scenario('Check obituary details', ({ I }) => {
    const randomName = faker.person.fullName(); 
    const randomEmail = faker.internet.email(); 

    I.amOnPage('/us/obituaries/chicagotribune/name/virginia-gruchalski-obituary?pid=196167379'); 
    I.see('Virginia Grace Gruchalski'); 
    I.scrollTo('//textarea[@form="guest-book-add"]')
    I.fillField('//textarea[@form="guest-book-add"]', 'This is generated by automation');
    I.fillField('//input[@name="_GuestbookForm_From"]', randomName); 
    I.fillField('//input[@name="_GuestbookForm_Email"]', randomEmail); 
    I.click('//button[@data-component="AffiliateGuestbookSubmitButton"]'); 
    I.dontSeeElement('//textarea[@form="guest-book-add"]');
})