const { I } = require('../helpers/helper'); 

class ObituaryDetailsPage {
    constructor() {
        this.messageField = '[name="_GuestbookForm_Message"]';
        this.nameField = '[name="_GuestbookForm_From"]';
        this.emailField = '[name="_GuestbookForm_Email"]';
        this.submitButton = '[data-component="AffiliateGuestbookSubmitButton"]';
        this.successMessage = '[data-component="AffiliateGuestbookSuccessBox"]';
    }

    goToPage(url) {
        I.amOnPage(url);
    }

    verifyTitleVisible(obituaryTitle) {
        I.see(obituaryTitle);
    }

    fillGuestBookMessage(name, email) {
        I.scrollTo(this.messageField);
        I.fillField(this.messageField, 'This is generated by automation');
        I.fillField(this.nameField, name);
        I.fillField(this.emailField, email);
    }

    submitForm() {
        I.click(this.submitButton);
    }

    verifySuccessMessageVisible() {
        I.waitForVisible(this.successMessage, 2);
        I.seeElement(this.successMessage);
    }
}

module.exports = new ObituaryDetailsPage();